# Generated by Django 5.0.7 on 2024-07-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='drive_license_num',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Серия и номер водительской лицензии'),
        ),
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='users',
            name='passport_num',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Серия и номер паспорта'),
        ),
    ]
