# Generated by Django 5.0.7 on 2024-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_drive_license_num_users_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='drive_license_num',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Серия и номер водительской лицензии'),
        ),
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Отчество'),
        ),
    ]
