# Generated by Django 5.0.7 on 2024-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_drive_license_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='passport_num',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Серия и номер паспорта'),
        ),
    ]
