# Generated by Django 5.0.7 on 2024-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_middle_name_alter_users_passport_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
    ]
