# Generated by Django 5.0.7 on 2024-07-25 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carcase_name', models.CharField(max_length=15, unique=True, verbose_name='Название кузова')),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=15, unique=True, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=15, unique=True, verbose_name='Название производителя')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('power', models.IntegerField(verbose_name='Лошадиные силы')),
                ('carcase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.carcases', verbose_name='Кузов')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='cars.carmodels', verbose_name='Название модели')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.designers', verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='BusyCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_start', models.DateField(verbose_name='Начало аренды')),
                ('busy_end', models.DateField(verbose_name='Конец аренды')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='busycars_set', to='cars.carinstances', verbose_name='ID машины')),
            ],
            options={
                'verbose_name': 'Занятая машина',
                'verbose_name_plural': 'Занятые машины',
            },
        ),
        migrations.AddField(
            model_name='carmodels',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.designers', verbose_name='Производитель'),
        ),
        migrations.AddConstraint(
            model_name='busycars',
            constraint=models.CheckConstraint(check=models.Q(('busy_start__lte', models.F('busy_end'))), name='check_busy_dates'),
        ),
    ]
